openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/LONGLEVANQUOC/pay-visibility-service/1.0.1
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/LONGLEVANQUOC/swagger-hub/1.0.0
info:
  version: 1.0.1
  title: Swagger-hub
  description: Sample design api swagger hub
paths:
  /swagger-hub:
    get:
      summary: Get api
      description: Get api
      responses:
        '200':
          description: Get api
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SwaggerDto'
      tags: 
        - swagger-hub
    post:
      summary: Post api
      description: Post api
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SwaggerRequest'
      responses:
        '200':
          description: Post api.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SwaggerDto'
      tags: 
        - swagger-hub
components:
  schemas:
    SwaggerDto:
      type: object
      properties:
        courierId:
          type: string
        date:
          type: string
          format: date
        totalPay:
          type: number
          format: double
        lastUpdatedAt:
          type: string
          format: date-time
    SwaggerRequest:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the courier
        name:
          type: string
          description: Name of the courier
        courierType:
          type: string
          description: Type of the courier
        applicantId:
          type: string
          description: Identifier of the applicant